version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@1.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'

workflows:
  build:
    jobs:
      - cypress/run