version: 2.1
orbs:
  cypress: cypress-io/cypress@1.16.1
  node: circleci/node@1.1

executors:
  chrome80-ff72:
    docker:
      - image: 'cypress/browsers:node13.6.0-chrome80-ff72'

workflows:
  build:
    jobs:
      - cypress/run: 
          requires:
            - cypress/install
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          # Runs jobs in parallel
          # https://docs.cypress.io/guides/guides/parallelization
          parallel: true
          parallelism: 2 # Uses 2 parallel instances
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          start: npm start
          wait-on: 'http-get://localhost:3000' # Waits for above